### ISSUE TITLE
Unable to generate sealed set for new Lord of the Rings or March of the machines Aftermath

### ISSUE THREAD

**Issue by dougnukem** [fverdoja/booster-tutor#6]
Thanks for putting out this discord bot.

I'm looking to use it to generate sealed deck booster for the new sets, but the discord bot doesn't seem to be picking the new sets.
- https://mtgjson.com/downloads/all-sets/

```
# MTG Lord of the Rings
!setsealed LTR

# MTG Rise of the Machines after math
!setsealed  AMOM
```

Also tried generating from a Cube that contains the LOTR set (which makes sense if the bot doesn't have that set loaded).
https://cubecobra.com/cube/overview/e1a51d49-9a07-48b1-b2ba-c78b6e65d03b

```
!cubesealed e1a51d49-9a07-48b1-b2ba-c78b6e65d03b
```

**Expected result**
Generate a sealed deck using that set code.

**Investigation**
It looks like the discord bot does initialize and load the sets from an API 
https://github.com/fverdoja/booster-tutor/blob/da733cf23f9d7310251af247831cd102190e364c/boostertutor/bot.py#L82-L85

Perhaps the main discord bot server just needs to be restarted to pick up the latest sets?

Also maybe there can be some logic added in the generator code to refresh from the MTG JSON API every 24 hours or something like that to pick up the new sets?

**Comment by fverdoja** [comment]
Hi Doug,
`!LTR` and `!MAT` (for Aftermath) work now (together with their `!setsealed` counterpart).

With regards to the cube command, the problem wasn't actually with LTR cards, but the APIs from cubecobra changed and I needed to adjust parsing on my side, so thanks for raising the issue. I have fixed the parsing, and now the command you mention should work.

> Also maybe there can be some logic added in the generator code to refresh from the MTG JSON API every 24 hours or something like that to pick up the new sets?

Thanks for the suggestion, but I don't plan to implement something like this, data from mtgjson is not always stable and complete, especially during spoiler season, so I prefer to update only when I know things are pretty much stable. I also have some automated checks when I load the data to verify some consistency in the data I'm loading, but don't cover all possible issues so I prefer to do things manually for now.

Finally, thanks a lot for the donation. It's really appreciated. :)
